repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        additional_dependencies: []
        args: [--config-file=pyproject.toml, src]
        pass_filenames: false
  - repo: local
    hooks:
      - id: pytest
        name: pytest (smoke)
        entry: pytest
        language: system
        args: ["-m", "smoke", "--tb=short"]
        pass_filenames: false
        stages: [commit]
